name: 🐛 Bug Report
description: Report a bug in the Ultimate Photorealistic Renderer
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Oh no! 😢 Something isn't working as expected. Don't worry, we'll fix it together! 💕
        Please help us understand what happened so we can make everything perfect again.

  - type: input
    id: bug-title
    attributes:
      label: 🎯 Bug Summary
      description: A clear and concise title for this bug
      placeholder: e.g., "Quantum light transport crashes on complex scenes"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: What happened? What did you expect to happen?
      placeholder: |
        Describe the bug clearly:
        - What were you trying to do?
        - What actually happened?
        - What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Set parameters to...
        4. See error
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: ⚠️ Severity Level
      description: How severe is this bug?
      options:
        - Critical (Crashes, data loss, security)
        - High (Major feature broken)
        - Medium (Feature partially working)
        - Low (Minor issue, workaround exists)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Affected Component
      description: Which part of the renderer is affected?
      options:
        - Quantum Algorithms
        - AI Physics Bypass
        - Electromagnetic Rendering
        - Ray Tracing Core
        - WebGL/GPU Interface
        - User Interface
        - Performance System
        - Testing Framework
        - Documentation
        - Unknown
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Technical details about your setup
      placeholder: |
        - OS: (e.g., macOS 14.0, Windows 11, Ubuntu 22.04)
        - Browser: (e.g., Chrome 120, Safari 17, Firefox 119)
        - GPU: (e.g., RTX 4090, M3 Max, Intel Iris)
        - Screen Resolution: (e.g., 4K, 1440p, 1080p)
        - Any other relevant specs
    validations:
      required: true

  - type: textarea
    id: console-output
    attributes:
      label: 📜 Console Output / Error Messages
      description: Any error messages or console output?
      placeholder: |
        Please paste any error messages, stack traces, or console output here.
        
        ```
        Error messages go here
        ```

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✨ Expected Behavior
      description: What should have happened instead?
      placeholder: Describe the correct behavior you expected to see

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: Visual evidence of the issue (if applicable)
      placeholder: |
        Drag and drop images here, or paste screenshot URLs
        Videos are especially helpful for rendering issues!

  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 Additional Context
      description: Anything else that might be relevant?
      placeholder: |
        - Does this happen consistently or intermittently?
        - Any workarounds you've found?
        - Related to recent changes?
        - Performance impact?

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please confirm you've done these steps
      options:
        - label: I've searched existing issues for this bug
          required: true
        - label: I've included all requested information
          required: true
        - label: I can reproduce this bug consistently
          required: false
        - label: I've tested in multiple browsers (if applicable)
          required: false