blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/nao-amj/three-hearts-raytracer/discussions
    about: Ask questions, share ideas, or discuss the future of photorealistic rendering
  - name: 🌟 Three Hearts Space
    url: https://github.com/nao-amj/
    about: Explore more projects created with love by Yuki & Miki
  - name: 📚 Documentation
    url: https://github.com/nao-amj/three-hearts-raytracer/wiki
    about: Comprehensive guides and technical documentation