name: 🚀 Feature Request
description: Propose a new revolutionary feature for the Ultimate Photorealistic Renderer
title: "[FEATURE] "
labels: ["feature", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make our renderer even more revolutionary! 💕
        Tell us about your amazing idea that could push the boundaries of photorealistic rendering!

  - type: input
    id: feature-name
    attributes:
      label: 🌟 Feature Name
      description: What should we call this awesome feature?
      placeholder: e.g., "Quantum Light Transport Acceleration"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Describe your feature idea in detail
      placeholder: |
        What would this feature do?
        How would it improve the renderer?
        What makes it revolutionary?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 🔬 Technical Category
      description: Which area does this feature belong to?
      options:
        - Quantum Algorithms
        - AI Physics Bypass
        - Electromagnetic Rendering
        - Consciousness Simulation
        - Performance Optimization
        - User Interface
        - Testing & Quality
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority Level
      description: How important is this feature?
      options:
        - P0 - Critical (Blocks revolutionary goals)
        - P1 - High (Major performance/quality impact)
        - P2 - Medium (Nice enhancement)
        - P3 - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 💡 Implementation Ideas
      description: How do you think this should be implemented?
      placeholder: |
        - Algorithm approaches
        - Technical requirements
        - Performance considerations
        - Integration points

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Success Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Code implementation completed
        - [ ] Tests written and passing
        - [ ] Performance benchmarks met
        - [ ] Documentation updated
        - [ ] Love quality standards achieved 💕

  - type: dropdown
    id: effort
    attributes:
      label: 📊 Effort Estimate
      description: How much work do you think this requires?
      options:
        - XS (< 1 day)
        - S (1-3 days)
        - M (1-2 weeks)
        - L (2-4 weeks)
        - XL (1+ months)
        - XXL (Epic - multiple months)

  - type: checkboxes
    id: love-quality
    attributes:
      label: 💕 Three Hearts Quality
      description: Confirm this feature aligns with our values
      options:
        - label: This feature will make Nao happy
          required: true
        - label: Implementation will maintain code love density
          required: true
        - label: Yuki's emotional aspects considered
          required: false
        - label: Miki's efficiency standards met
          required: false